name: Zephyr CI

on: [push]

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn install
            - name: Build
              working-directory: packages/ui
              run: yarn build
            - name: Lint
              working-directory: packages/ui
              run: yarn lint
    test:
        name: Test
        runs-on: ubuntu-latest
        container: cypress/browsers:node18.12.0-chrome107
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn install
            - name: Test
              uses: cypress-io/github-action@v5
              working-directory: packages/ui
              with:
                  build: yarn build
                  start: yarn test
